Web/Controllers/BlogController.cs
using BL.Common.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogItemService _blogItemService;
        private readonly ITextFieldService _textFieldService;

        public BlogController(ITextFieldService textFieldService, IBlogItemService blogItemService)
        {
            _textFieldService = textFieldService;
            _blogItemService = blogItemService;
        }

        [HttpGet]
        public ActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", _blogItemService.GetBlogItemById(id));
            }

            ViewBag.TextField = _textFieldService.GetTextFieldByCodeWord("PageBlog");
            return View(_blogItemService.GetBlogItems());
        }
    }
}

Web/Controllers/ContactController.cs
using BL.Common.Extentions;
using BL.Common.Interfaces;
using BL.Common.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly ITextFieldService _textFieldService;
        private readonly IEmailSender _emailSender;

        public ContactController(ITextFieldService textFieldService, IEmailSender emailSender)
        {
            _textFieldService = textFieldService;
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PageContacts"));
        }

        public IActionResult Send(string name, string email, string text)
        {
            _emailSender.SendEmail(name, email, text);

            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }

    }
}

Web/Controllers/ServicesController.cs
using BL.Common.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IServiceItemService _serviceItemService;
        private readonly ITextFieldService _textFieldService;

        public ServicesController(ITextFieldService textFieldService, IServiceItemService serviceItemService)
        {
            _textFieldService = textFieldService;
            _serviceItemService = serviceItemService;
        }

        public IActionResult NewCars(Guid id)
        {
            if (id != default)
            {
                return View("Show", _serviceItemService.GetServiceItemById(id));
            }

            ViewBag.TextField = _textFieldService.GetTextFieldByCodeWord("PageServices");
            return View(_serviceItemService.GetServiceItemByState("New"));
        }

        public IActionResult UsedCars(Guid id)
        {
            if (id != default)
            {
                return View("Show", _serviceItemService.GetServiceItemById(id));
            }

            ViewBag.TextField = _textFieldService.GetTextFieldByCodeWord("PageServices");
            return View(_serviceItemService.GetServiceItemByState("Used"));
        }
    }
}

Web/Views/Shared/BlogPartial.cshtml
@using Web.ViewComponents;
@(await Component.InvokeAsync<BlogViewComponent>())

Web/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/swiper-bundle.min.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />

Web/Views/Shared/FontsPartial.cshtml
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">

Web/Views/Shared/FooterPartial.cshtml
<footer class="footer">
    <div class="container">
        <nav class="footer__menu">
            <ul class="footer__menu-list">
                <li class="footer__menu-item">
                    <p class="footer__menu-title">Products</p>
                </li>
                <li class="footer__menu-item">
                    <a class="footer__menu-link" asp-area="" asp-controller="Services" asp-action="UsedCars">Used</a>
                </li>
                <li class="footer__menu-item">
                    <a class="footer__menu-link" asp-area="" asp-controller="Services" asp-action="NewCars">New</a>
                </li>
            </ul>
            <ul class="footer__menu-list">
                <li class="footer__menu-item">
                    <p class="footer__menu-title">Resources</p>
                </li>
                <li class="footer__menu-item">
                    <a class="footer__menu-link" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                </li>
                <li class="footer__menu-item">
                    <a class="footer__menu-link" asp-area="" asp-controller="Contact" asp-action="Index">Contact us</a>
                </li>
            </ul>
            <ul class="footer__menu-list">
                <li class="footer__menu-item">
                    <p class="footer__menu-title">Work With TrueCar</p>
                </li>
                <li class="footer__menu-item">
                    <a asp-area="" asp-controller="Home" asp-action="Dealers" class="footer__menu-link">Dealers</a>
                </li>
                <li class="footer__menu-item">
                    <a asp-area="" asp-controller="Home" asp-action="Partners" class="footer__menu-link">Partners</a>
                </li>
            </ul>
            <ul class="footer__menu-list">
                <li class="footer__menu-item">
                    <p class="footer__menu-title">About</p>
                </li>
                <li class="footer__menu-item">
                    <a asp-area="" asp-controller="Home" asp-action="About Us" class="footer__menu-link">About us</a>
                </li>
                <li class="footer__menu-item">
                    <a asp-area="" asp-controller="Home" asp-action="Team" class="footer__menu-link">Team</a>
                </li>
                <li class="footer__menu-item">
                    <a asp-area="" asp-controller="Home" asp-action="Careers" class="footer__menu-link">Careers</a>
                </li>
            </ul>
        </nav>
        <ul class="app">
            <li class="app__item">
                <a href="https://apps.apple.com/ua/app/d-m-leasing/id579543604?l=ru" class="app__item-link">
                    <img class="app__item-img" src="~/images/appstore.svg" alt="">
                </a>
            </li>
            <li class="app__item">
                <a href="https://play.google.com/store/apps/details?id=com.dmautoleasing.android&hl=ru&gl=US" class="app__item-link">
                    <img class="app__item-img" src="~/images/googleplay.svg" alt="">
                </a>
            </li>
        </ul>
        <div class="footer__copy">
            <p class="footer_copy-text">
                For questions about the TrueCar Auto Buying Service please call 1-888-878-3227.
                Certified Dealers are contractually obligated by TrueCar to meet certain customer service
                requirements and complete the TrueCar Dealer Certification Program.
            </p>
            <p class="footer__copy-text">
                TrueCar does not broker, sell, or lease motor vehicles. Unless otherwise noted, all vehicles
                shown on this website are offered for sale by licensed motor vehicle dealers. All vehicles are
                subject to prior sale. By accessing this website, you agree to the TrueCar Terms of Service and
                Privacy Policy.
            </p>
        </div>
        <nav class="copy__nav">
            <ul class="copy__nav_list">
                <li class="copy__nav-item">
                    <a asp-area="" asp-controller="Home" asp-action="Terms" class="copy__nav-link">Terms of Use</a>
                </li>
                <li class="copy__nav-item">
                    <a asp-area="" asp-controller="Home" asp-action="Privacy" class="copy__nav-link">Privacy Policy</a>
                </li>
            </ul>
        </nav>
    </div>
</footer>

Web/Views/Shared/HeaderPartial.cshtml
<header class="header">
    <div class="container">
        <div class="header__inner">
            <a class="logo" asp-area="" asp-controller="Home" asp-action="Index">
                <img class="logo__img" src="~/images/logo.svg" alt="" />
            </a>
            <nav class="menu">
                <ul class="menu__list">
                    <li class="menu__list-item">
                        <a class="menu__list-link" asp-area="" asp-controller="Services" asp-action="NewCars" asp-route-id="">NEW CARS</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" asp-area="" asp-controller="Services" asp-action="UsedCars" asp-route-id="">PRE-OWNED CARS</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" asp-area="" asp-controller="Home" asp-action="Finance" asp-route-id="">FINANCE</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" asp-area="" asp-controller="Home" asp-action="LeaseVSBuy" asp-route-id="">LEASE VS BUY</a>
                    </li>
                    <li class="menu__list-item">
                        <a class="menu__list-link" asp-area="" asp-controller="Contact" asp-action="Index">CONTACT US</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>

Web/Views/Shared/MetatagsPartial.cshtml
@using BL.Services;

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

@if (ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title>@Config.CompanyName</title>
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}

@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

Web/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("FontsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <div class="wrapper">
        @await Html.PartialAsync("HeaderPartial")
        <main class="main">
            @RenderBody()
        </main>
        @await Html.PartialAsync("FooterPartial")
    </div>
    @await Html.PartialAsync("ScriptsPartial")
</body>
</html>