Web/Areas/Admin/Controllers/BlogItemsController.cs
using BL.Common.Extentions;
using BL.Common.Interfaces.Services;
using Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Web.Controllers;

namespace Web.Areas.Controllers
{
    [Area("Admin")]
    public class BlogItemsController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IBlogItemService _blogItemService;
        public BlogItemsController(IWebHostEnvironment webHostEnvironment, IBlogItemService blogItemService)
        {
            _webHostEnvironment = webHostEnvironment;
            _blogItemService = blogItemService;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new BlogItem() : _blogItemService.GetBlogItemById(id);
            return View(entity);
        }


        [HttpPost]
        public IActionResult Edit(BlogItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                _blogItemService.AddBlogItem(model);
                _blogItemService.UpdateBlogItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
           _blogItemService.DeleteBlogItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Web/Areas/Admin/Controllers/HomeController.cs
using BL.Common.Interfaces.Services;
using Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly IServiceItemService _serviceItemService;
        private readonly IBlogItemService _blogItemService;

        public HomeController(IServiceItemService serviceItemService, IBlogItemService blogItemService)
        {
            _serviceItemService = serviceItemService;
            _blogItemService = blogItemService;
        }

        public IActionResult Index()
        {
            ViewModel myModel = new ViewModel();
            myModel.ServiceItems = _serviceItemService.GetServiceItems();
            myModel.BlogItems = _blogItemService.GetBlogItems();
            return View(myModel);
        }
    }
}

Web/Areas/Admin/Controllers/ServiceItemsController.cs
using BL.Common.Extentions;
using BL.Common.Interfaces.Services;
using Core.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Controllers
{
    [Area("Admin")]
    public class ServiceItemsController : Controller
    {
        private readonly IServiceItemService _serviceItemService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ServiceItemsController(IWebHostEnvironment webHostEnvironment, IServiceItemService serviceItemService)
        {
            _webHostEnvironment = webHostEnvironment;
            _serviceItemService = serviceItemService;
        }

        public IActionResult Create(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                _serviceItemService.AddServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
           
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new ServiceItem() : _serviceItemService.GetServiceItemById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(_webHostEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                _serviceItemService.UpdateServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            _serviceItemService.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Web/Areas/Admin/Controllers/TextFieldsController.cs
using BL.Common.Extentions;
using BL.Common.Interfaces.Services;
using Core.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Web.Areas.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly ITextFieldService _textFieldService;

        public TextFieldsController(ITextFieldService textFieldService)
        {
            _textFieldService = textFieldService;
        }

        public IActionResult Edit(string codeWord)
        {
            _textFieldService.GetTextFieldByCodeWord(codeWord);
            return View();
        }

        [HttpPost]
        public IActionResult Edit(TextField model)
        {
            if (ModelState.IsValid)
            {
                _textFieldService.AddTextField(model);
                _textFieldService.UpdateTextField(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

Web/Controllers/HomeController.cs
using BL.Common.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITextFieldService _textFieldService;
        public HomeController(ITextFieldService textFieldService)
        {
            _textFieldService = textFieldService;
        }

        public IActionResult Index()
        {           
            return View(_textFieldService.GetTextFieldByCodeWord("PageIndex"));
        }

        public IActionResult Finance()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PageFinance"));
        }

        public IActionResult LeaseVSBuy()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PageLeaseVSBuy"));
        }

        public IActionResult Dealers()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PageDealers"));
        }

        public IActionResult Partners()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PagePartners"));
        }

        public IActionResult Terms()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PageTerms"));
        }

        public IActionResult Privacy()
        {
            return View(_textFieldService.GetTextFieldByCodeWord("PagePrivacy"));
        }


    }
}

Web/Controllers/ServicesController.cs
using BL.Common.Interfaces.Services;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class ServicesController : Controller
    {
        private readonly IServiceItemService _serviceItemService;
        private readonly ITextFieldService _textFieldService;

        public ServicesController(ITextFieldService textFieldService, IServiceItemService serviceItemService)
        {
            _textFieldService = textFieldService;
            _serviceItemService = serviceItemService;
        }

        public IActionResult NewCars(Guid id)
        {
            if (id != default)
            {
                return View("Show", _serviceItemService.GetServiceItemById(id));
            }

            ViewBag.TextField = _textFieldService.GetTextFieldByCodeWord("PageServices");
            return View(_serviceItemService.GetServiceItemByState("New"));
        }

        public IActionResult UsedCars(Guid id)
        {
            if (id != default)
            {
                return View("Show", _serviceItemService.GetServiceItemById(id));
            }

            ViewBag.TextField = _textFieldService.GetTextFieldByCodeWord("PageServices");
            return View(_serviceItemService.GetServiceItemByState("Used"));
        }
    }
}

Web/Areas/Admin/Views/Home/Index.cshtml
@model ViewModel
@{
    string strTitle = "Admin Panel";
    ViewBag.Title = strTitle;
}

<div class="container">
    <h1 class="page-title">@strTitle</h1>
    <h2 class="block__title">Services</h2>
    <section class="services">
        <table>
            <caption class="table-caption">New cars</caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            @foreach (ServiceItem entity in Model.ServiceItems)
            {
                if (entity.State == "New")
                {
                    <tr>
                        <td>
                            <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                                @($"{entity.Title}")
                            </a>
                        </td>
                        <td>
                            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">edit</a>
                        </td>
                        <td>
                            <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                                <input type="hidden" name="id" value="@entity.Id">
                                <a onclick="document.getElementById('form-@entity.Id').submit();">delete</a>
                            </form>
                        </td>
                    </tr>
                }
            }
        </table>
        <table>
            <caption class="table-caption">Pre-owned cars</caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            @foreach (ServiceItem entity in Model.ServiceItems)
            {
                if (entity.State == "Used")
                {
                    <tr>
                        <td>
                            <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                                @($"{entity.Title}")
                            </a>
                        </td>
                        <td>
                            <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">edit</a>
                        </td>
                        <td>
                            <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                                <input type="hidden" name="id" value="@entity.Id">
                                <a onclick="document.getElementById('form-@entity.Id').submit();">delete</a>
                            </form>
                        </td>
                    </tr>
                }
            }
        </table>
        <a class="add" asp-area="Admin" asp-controller="ServiceItems" asp-action="Create" asp-route-id="">Add service</a>
    </section>
    <section class="blog-edit">
        <h2 class="block__title">Blog</h2>
        <table class="table">
            <caption class="table-caption">Blog Item</caption>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            @foreach (BlogItem entity in Model.BlogItems)
            {
                <tr>
                    <td>
                        <a asp-area="" asp-controller="BlogItems" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </td>
                    <td>
                        <a asp-area="Admin" asp-controller="BlogItems" asp-action="Edit" asp-route-id="@entity.Id">edit</a>
                    </td>
                    <td>
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="BlogItems" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a onclick="document.getElementById('form-@entity.Id').submit();">delete</a>
                        </form> 
                    </td>
                </tr>
            }
        </table>
        <a class="add" asp-area="Admin" asp-controller="BlogItems" asp-action="Edit" asp-route-id="">Add blog item</a>
    </section>
    <section class="pages">
        <h2 class="block__title">Edit site pages</h2>
        <a class="edit-page__site" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Home</a>
        <a class="edit-page__site" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Services</a>
        <a class="edit-page__site" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Contacts</a>
        <a class="edit-page__site" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageBlog">Blog</a>
        <div class="exit_btn">
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
                <input class="form__btn" type="submit" value="Exit" />
            </form>
        </div>
    </section>
</div>